table 財務
	lineageTag: 671564c8-2c7a-46f9-bc99-745d4ee5e71f

	measure 総利益 = SUM('財務'[Profit])
		lineageTag: 84168670-cd52-4821-9654-5e1b9b7eee8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 総売上 = SUM('財務'[Sales])
		lineageTag: d8bcb4ca-4624-4ae4-9c4e-d8691817f466

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 販売額合計 = SUM('財務'[Sale Price])
		formatString: 0
		lineageTag: f12fe350-94b9-4f45-9779-42901297dcfa

	measure 数量 = SUM('財務'[Units Sold])
		lineageTag: 14d3dddb-9fff-4a47-b51b-c2e33560a203

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 売上単価 = DIVIDE([総売上], [数量], BLANK())
		lineageTag: 627f1fe9-bbee-457e-a3ea-90bb006ed2d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 利益単価 = DIVIDE([総利益], [数量], BLANK())
		lineageTag: 3aef43e3-246d-4d75-8ab1-0a4062966f5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Segment
		dataType: string
		lineageTag: 4ae4f203-b511-4bcb-afec-75d49b349201
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 65b1a000-0988-4b41-9b7d-d2efabfa13b8
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: b8836118-7eab-49b3-87da-c232c51db5fa
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: d0a3c9da-5cc5-4324-9659-a3901a7dc95c
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: 39cad347-2769-4651-b032-de08026d2ada
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: f160a85c-d066-4818-a22d-fb4e9e9897dd
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: d0871418-b735-42da-866d-a6635d93126d
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 44dd405a-55a2-4dc3-8b6c-6c26d2347ee3
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: df8c5168-ea2a-49f8-b476-6cdfd370c3bf
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 5a8cc8c2-891f-4dd6-8ca4-ba7f24d432e3
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: a4308f46-3909-48c1-880d-de098bc391e8
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: e83438e7-a5b1-4e9d-9e54-d1f85c3c5214
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5fa036af-f7e3-415d-b10f-d8a8eb62d460
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 財務 = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.147.1085.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    変更された型 = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}),
				    削除された列 = Table.RemoveColumns(変更された型,{"Month Number", "Month Name", "Year"})
				in
				 削除された列

	annotation PBI_NavigationStepName = ナビゲーション

	annotation PBI_ResultType = Table

